# PostgreSQL config - Rails 7

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mequi_ai_development

test:
  <<: *default
  database: mequi_ai_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
